#!/bin/bash

buildkite-agent meta-data set "graphite-should-skip-ci" "true"

# Check condition
if [[ "${SHOULD_RUN}" != "true" ]]; then
  echo "CI does not need to run; skipping now"
  # Cancel the job
#   buildkite-agent job update --status canceled

  # Next, try changing the agent workflow
  # echo "Trying to skip the pipeline"
  # buildkite-agent pipeline upload --replace "${BUILDKITE_PLUGINS_PATH}/github-com-pinkerton-ci-skipper-buildkite-plugin-main/custom-ci-skipping-pipeline.yml"
  buildkite-agent annotate ":graphite: This PR is in the middle of a [stack](https://stacking.dev)
                            and will not run CI until it configured to do so, or is manually triggered." --style "info" --context "graphite" --job $BUILDKITE_JOB_ID
  buildkite-agent pipeline upload --replace "${BUILDKITE_PLUGINS_PATH}/github-com-pinkerton-ci-skipper-buildkite-plugin-main/skip-ci-2.yml"
  echo "build should be skipped"
  exit 0
fi

echo "Condition met, continuing with the job."
exit 0