#!/bin/bash

# Check condition
if [[ "${SHOULD_RUN}" != "true" ]]; then
  echo "CI does not need to run; skipping now"
  # Cancel the job
#   buildkite-agent job update --status canceled

  # Next, try changing the agent workflow
  # echo "Trying to skip the pipeline"
  # buildkite-agent pipeline upload --replace "${BUILDKITE_PLUGINS_PATH}/github-com-pinkerton-ci-skipper-buildkite-plugin-main/custom-ci-skipping-pipeline.yml"
  buildkite-agent pipeline upload --replace "${BUILDKITE_PLUGINS_PATH}/github-com-pinkerton-ci-skipper-buildkite-plugin-main/skip-ci-2.yml"
  exit 0
fi

echo "Condition met, continuing with the job."